"""Step 2: auto-label extracted frames with the current detector.

    python -m scripts.prelabel

Writes YOLO-format labels (training/dataset/labels/{train,val}/<img>.txt) and
training/dataset/data.yaml. These are *pseudo-labels* — a starting point so you
correct boxes instead of drawing from scratch. The off-the-shelf detector is
good at `person`/`cup` and weak at `phone` (that's the whole reason we're
fine-tuning), so expect to ADD most phone boxes yourself in the labeler.

YOLO label line:  <class_idx> <cx> <cy> <w> <h>   (all normalized 0..1)
"""
from __future__ import annotations
import sys
from pathlib import Path
import cv2

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from src.detector import ProductDetector  # noqa: E402
from training.classes import CLASSES, PRELABEL_MAP  # noqa: E402

DS = ROOT / "training/dataset"


def label_split(det, split: str) -> int:
    img_dir = DS / "images" / split
    lab_dir = DS / "labels" / split
    lab_dir.mkdir(parents=True, exist_ok=True)
    n = 0
    for img in sorted(img_dir.glob("*.jpg")):
        frame = cv2.imread(str(img))
        if frame is None:
            continue
        h, w = frame.shape[:2]
        lines = []
        for d in det.detect(frame):
            idx = PRELABEL_MAP.get(d.label.lower())
            if idx is None:
                continue
            x1, y1, x2, y2 = d.box
            cx = ((x1 + x2) / 2) / w; cy = ((y1 + y2) / 2) / h
            bw = (x2 - x1) / w; bh = (y2 - y1) / h
            lines.append(f"{idx} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}")
        (lab_dir / f"{img.stem}.txt").write_text("\n".join(lines))
        n += 1
    return n


def write_yaml():
    yaml = DS / "data.yaml"
    names = "\n".join(f"  {i}: {c}" for i, c in enumerate(CLASSES))
    yaml.write_text(
        f"# auto-generated by prelabel.py\n"
        f"path: {DS}\n"
        f"train: images/train\n"
        f"val: images/val\n"
        f"names:\n{names}\n"
    )
    print("wrote", yaml)


def main():
    det = ProductDetector(conf=0.15)  # low conf => more boxes to correct
    print("detector mode:", det.mode)
    for split in ("train", "val"):
        n = label_split(det, split)
        print(f"pre-labeled {n} {split} images")
    write_yaml()
    print("Next: correct the boxes with scripts/label.py, then scripts/train.py")


if __name__ == "__main__":
    main()
